title: Edward Im\'s Blog

description: > # this means to ignore newlines until "baseurl:"
    Hello guys :-)

permalink: ':title/'

baseurl: # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Edward Im # add your name
author-img: tigerk.png # add your photo
about-author: Edward\'s blog :-) # add description
twitter: # add your Twitter handle
facebook: tigerk0430 # add your Facebook handle
github: lockdpwn # add your Github handle
linkedin: # add your Linkedin handle
email: gyurse@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier


# Tracker
analytics: # Google Analytics


# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
