title: Edward Im`s Blog

description: > # this means to ignore newlines until "baseurl:"

permalink: ':title/'

baseurl: # the subpath of your site, e.g. /blog

url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Edward Im
author-img: tigerk.png 
about-author: Edward`s blog # add description
facebook: tigerk0430 
github: tigerk0430 
email: gyurse@gmail.com 

# Disqus
discus-identifier: mr-brown # add your discus identifier

# 페이지 구분을 하기 위한 코드 추가
paginate: 1
paginate_path: "blog/:num/"

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Categories
   url: /category
 - title: Contact
   url: /contact
  
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
